baseURL: "https://xuyafei.github.io/myblog"
languageCode: "zh-cn"
title: "My Blog"
theme: "PaperMod"

pagination:
  pagerSize: 5

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production
  title: "徐亚飞的技术博客"
  description: "分享技术与开发经验的个人博客"
  keywords: [博客, 技术, 开发, 编程]
  author: 徐亚飞
  DateFormat: "2006年1月2日"
  defaultTheme: auto
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  ShowToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: false

  profileMode:
    enabled: true
    title: "欢迎来到我的博客" 
    subtitle: "这里是我分享技术思考和开发经验的空间"
    imageUrl: "/myblog/images/avatar.png"
    imageTitle: "徐亚飞" 
    imageWidth: 120
    imageHeight: 120
    buttons:
      - name: 文章列表
        url: posts
      - name: 关于我
        url: about

  socialIcons:
    - name: github
      url: "https://github.com/xuyafei"
    # 如果您有其他社交媒体账号，可以在这里添加

  assets:
    disableHLJS: true
    disableFingerprinting: true
    favicon: "<link / abs url>"
    favicon16x16: "<link / abs url>"
    favicon32x32: "<link / abs url>"
    apple_touch_icon: "<link / abs url>"
    safari_pinned_tab: "<link / abs url>"

menu:
  main:
    - identifier: categories
      name: 分类
      url: /categories/
      weight: 10
    - identifier: tags
      name: 标签
      url: /tags/
      weight: 20
    - identifier: archives
      name: 归档
      url: /archives/
      weight: 30
    - identifier: about
      name: 关于
      url: /about/
      weight: 40 